-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50)                             NOT NULL,
    email VARCHAR(150)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- Таблица вещей
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(500)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL DEFAULT true,
    owner_id    BIGINT                                  NOT NULL
        CONSTRAINT fk_items_owner_users_id
            REFERENCES users (id) ON DELETE CASCADE,
    request     BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS fk_items_owner_id ON items (owner_id);

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id        BIGINT                                  NOT NULL
        CONSTRAINT fk_comments_item_id_items_id REFERENCES items (id) ON DELETE CASCADE,
    text           VARCHAR(500)                            NOT NULL,
    created        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author_name_id BIGINT                                  NOT NULL
        CONSTRAINT fk_comments_author_id_users_id REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS fk_comments_item_id ON comments (item_id);
CREATE INDEX IF NOT EXISTS fk_comments_author_id ON comments (author_name_id);

-- Таблица бронирования
CREATE TABLE IF NOT EXISTS bookings
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id      BIGINT                                  NOT NULL
        CONSTRAINT fk_bookings_item_id_items_id REFERENCES items (id) ON DELETE CASCADE,
    booking_from TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    booking_to   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    booker_id    BIGINT
        CONSTRAINT fk_bookings_booker_id_users_id REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS fk_bookings_item_id ON bookings (item_id);
CREATE INDEX IF NOT EXISTS fk_bookings_booker_id ON bookings (booker_id);